### ISSUE TITLE
Using the example table mutator results in an empty table

### ISSUE THREAD

**Issue by grandpalacko** [jacksleight/statamic-bard-mutator#10]
## Bug Description
I tried to use the table mutator example from the documentation, but the end result was an empty table and the table's body printed after the table.

Expected result:

```
<div class="table-wrapper">
  <table>
    <tbody>
      <tr>
        <th rowspan="1" colspan="1"><p>Heading&nbsp;1</p></th>
        <th rowspan="1" colspan="1"><p>Heading&nbsp;2</p></th>
        <th rowspan="1" colspan="1"><p>Heading&nbsp;3</p></th>
      </tr>
      <tr>
        <td rowspan="1" colspan="1"><p>A</p></td>
        <td rowspan="1" colspan="1"><p>B</p></td>
        <td rowspan="1" colspan="1"><p>C</p></td>
      </tr>
      <tr>
        <td rowspan="1" colspan="1"><p>D</p></td>
        <td rowspan="1" colspan="1"><p>E</p></td>
        <td rowspan="1" colspan="1"><p>F</p></td>
      </tr>
    </tbody>
  </table>
</div>
```

Actual result:

```
<div class="table-wrapper">
  <table>
    <tbody></tbody>
  </table>
  <p>Heading&nbsp;1</p>
  <p>Heading&nbsp;2</p>
  <p>Heading&nbsp;3</p>
  <p>A</p>
  <p>B</p>
  <p>C</p>
  <p>D</p>
  <p>E</p>
  <p>F</p>
</div>
```

## How to Reproduce
1. Create a Bard field with the Table button enabled
2. Use the code from the [Add a wrapper div around all tables](https://jacksleight.dev/docs/bard-mutator/installation#add-a-wrapper-div-around-all-tables) example
3. Add a table to the content field and check the result on the frontend

## Environment
Environment
Application Name: Statamic
Laravel Version: 9.52.4
PHP Version: 8.1.16
Composer Version: 2.5.4
Environment: local
Debug Mode: ENABLED
URL: bard-mutator-test.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: regex
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.4 Solo

**Comment by jacksleight** [comment]
It is wrong! Sorry about that, this is what it should be:

```php
Mutator::html('table', function ($value) {
    $inner = array_splice($value, 2, count($value), [0]);
    $value = ['div', ['class' => 'table-wrapper'], $value, ...$inner];
    return $value;
});
```

I'll get the docs updated accordingly.
