### ISSUE TITLE
Typo in Data Mutators Example? list_item vs. listItem

### ISSUE THREAD

**Issue by marflow** [jacksleight/statamic-bard-mutator#15]
Hello Jack, thanks a lot for publishing this very useful plugin! 

Just a short feedback for the docs: I tried to remove the paragraphs inside the list items with the code given on https://jacksleight.dev/docs/bard-mutator/mutators. That did not work. However the code given on https://jacksleight.dev/docs/bard-mutator/examples does. In this example you use `listItem`, on the mutators page `list_item`.
Might be a typo?

**Comment by jacksleight** [comment]
Hey. Yep, `list_item` is from v1/Tiptap 1 that used snake case names, must have missed that one when I updated the docs. All fixed, thanks for letting me know!
