### ISSUE TITLE
Docs Examples Doubled-Up

### ISSUE THREAD

**Issue by twd3** [jacksleight/statamic-bard-mutator#17]
## Bug Description
On your docs page the examples are doubled-up. 
![Untitled-1](https://user-images.githubusercontent.com/16004958/233480627-ff906edb-b572-4f67-b3f2-e1ec14ba97c4.jpg)

## How to Reproduce
Go to : https://jacksleight.dev/docs/bard-mutator/examples and look at example code.

## Extra Detail
You rule! I love your work!

**Comment by jacksleight** [comment]
Oh yeah, that happens every now and again, seems to be caused by some random glitch with the Torchlight code highlighting. Haven't managed to figure out a long term fix yet but clearing the cache works. 👍

Thanks for letting me know!
