### ISSUE TITLE
Duplicate code examples?

### ISSUE THREAD

**Issue by stephenmeehanuk** [jacksleight/statamic-bard-mutator#18]
Hi, 

Great add-on! Noticed, it looks like the code examples show duplicated code?
https://jacksleight.dev/docs/bard-mutator/examples#using-with-the-bard-modifiers

<img width="920" alt="Screenshot 2023-05-12 at 12 03 28" src="https://github.com/jacksleight/statamic-bard-mutator/assets/72254741/b1926e4a-3af7-4ce0-8401-ca0d578d993f">

**Comment by jacksleight** [comment]
Ah thanks for letting me know, this happens when Torchlight (the code highlighter) fails, which seems to happen randomly and I'm yet to figure out why.

I've cleared the cache it and it's OK now.
