### ISSUE TITLE
Move node up one level

### ISSUE THREAD

**Issue by daun** [jacksleight/statamic-bard-mutator#24]
Is it possible to move a node up by one level? Haven't seen an example for that in the docs and haven't found an obvious angle yet.

I'm trying to turn this:

```html
<blockquote>
  <p>Lorem ipsum dolor sit amet</p>
  <p>— Publius Vergilius Maro</p>
</blockquote>
```

Into this:

```html
<figure class="quote">
  <blockquote>
    <p>Lorem ipsum dolor sit amet</p>
  </blockquote>
  <figcaption>
    Publius Vergilius Maro
  </figcaption>
</figure>
```

I managed to turn the last paragraph into a `figcaption`, but it's nested under the blockquote, and I'd like to move it up into the `figure` itself for better semantics.

```php
// Wrap blockquote inside <figure>
Mutator::html('blockquote', function ($value, $data) {
    $inner = array_splice($value, 2, count($value), [0]);
    $value = ['figure', ['class' => 'quote'], $value, ...$inner];
    return $value;
});

// Wrap author on last quote line inside <figcaption>
Mutator::html('paragraph', function ($value, $data, $meta) {
    $isInBlockquote = ($meta['parent']->type ?? null) === 'blockquote';
    if ($isInBlockquote) {
        $isLastChild = !$meta['next'] && $meta['prev'];
        if ($isLastChild) {
            $source = Arr::last($data->content, fn($node) => $node->type === 'text' && Str::startsWith($node->text, ['-', '–', '—']));
            if ($source) {
                $source->text = Str::chopStart($source->text, ['-', '–', '—']);
                $value[0] = 'figcaption';
            }
        }
    }
    return $value;
});
```

**Comment by jacksleight** [comment]
Yes, you can use a [data mutator](https://jacksleight.dev/docs/bard-mutator/mutators#data-mutators) to do that, these allow you to modify the raw Prosemirror data before any rendering starts.

You can't do it in an HTML mutator since by the time you get to the child the parent's HTML has already been decided.

**Comment by daun** [comment]
Fantastic! I somehow thought the data mutators didn't apply here, but I'll give it a go. Thanks 🧃
