### ISSUE TITLE
Table of Contents example no longer works after the upgrade to 3.0.2

### ISSUE THREAD

**Issue by helloDanuk** [jacksleight/statamic-bard-mutator#35]
## Bug Description

After upgrading Bard Mutator to 3.0.2 I get an error `Undefined property: stdClass::$bard` when using the Table of Contents example here https://jacksleight.dev/docs/bard-mutator/examples#using-with-the-bard-modifiers

As far as I have found out so far, it is due to `{{ content | bard_html }}` inside the a-tag. If I remove this, everything else still works fine.

## How to Reproduce

I use the examples from the docs

AppServiceProvider.php
```
use Illuminate\Support\Str;
use JackSleight\StatamicBardMutator\Facades\Mutator;

…

Mutator::html('heading', function ($value, $item) {
    if ($item->attrs->level === 2) {
        $value[1]['id'] = Str::slug(collect($item->content)->implode('text', ''));
    }
    return $value;
});
```

Template View
```
{{ headings = hauptinhalt | raw | bard_items | where('type', 'heading') }}
{{ headings }}
    <a href="#{{ content | bard_text | slugify }}">{{ content | bard_html }}</a>
{{ /headings }}
```

## Environment

Environment
Application Name: Teilzeitbau Gebäudehülle CMS
Laravel Version: 11.28.0
PHP Version: 8.3.12
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: /
Maintenance Mode: OFF
Timezone: Europe/Zurich
Locale: de_CH

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 5
Sites: 3 (DE, FR, IT)
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.31.0 PRO

Statamic Addons
aryehraber/statamic-color-extractor: 1.5.0
jacksleight/statamic-bard-mutator: 3.0.2
mitydigital/statamic-sticky-notes: 1.0.2
statamic/seo-pro: 6.3.0
swiftmade/statamic-clear-assets: 3.1.0

**Comment by jacksleight** [comment]
Thanks for the report, fixed in v3.0.3.
