### ISSUE TITLE
List_item not working

### ISSUE THREAD

**Issue by pitcher-maarten** [jacksleight/statamic-bard-mutator#7]
```
Mutator::data('list_item', function ($data) {
    ...
});
```

It seems like the `list_item` data mutator is not getting triggered. 
All `mutator:tag`s work like aspected.

**Comment by jacksleight** [comment]
Are other data mutators working or is it just `list_item`? If none are working are you using the tag? (https://jacksleight.github.io/statamic-bard-mutator/rendering.html) That's required to use data mutators.

**Comment by pitcher-maarten** [comment]
Aha we are using the addon along the Content API so that sounds logic. Is there any way to accomplish this with the tag mutator?

**Comment by jacksleight** [comment]
Outside of antlers you can use the `Mutator::render` method to do the same thing (https://jacksleight.github.io/statamic-bard-mutator/rendering.html#direct) via a custom resource (https://statamic.dev/rest-api#customizing-resources).

Something like:

```php
class CustomEntryResource extends EntryResource
{
    public function toArray($request)
    {
        return [
            'my_content' => Mutator::render($this->resource->augmentedValue('my_content'));
        ];
    }
}
```

**Comment by jacksleight** [comment]
> Is there any way to accomplish this with the tag mutator?

What are you trying to do, can you share the full mutator code?

**Comment by pitcher-maarten** [comment]
Well what I want to achieve is that all Bard fields, no matter in what data structure, get cleaned up. One of the things I want to clean up is removing the paragraph nodes inside list items. 

So the best way to remove them would be by using the Mutator::tag I think?

**Comment by jacksleight** [comment]
Removing nodes is a mutation to the structure, so data mutators are the right tool for the job here. Many mutations aren’t possible via tag mutators which is why data mutators exist. However, removing the paragraphs from list items is _technically_ possible with a tag mutator, albeit not officially supported.

If you can’t use a data mutator this should do it instead:

```php
Mutator::tag(‘list_item’, function ($tag, $data) {
    if (($data->content[0]->type ?? null) === ‘paragraph’) {
        $data->content = $data->content[0]->content;
    }
    return $tag;
});
```
